### ISSUE TITLE
Err: raise informative error message if comparing nw.DataFrames backed by different libraries (e.g. pandas and Polars)

### ISSUE THREAD

**Issue by DeaMariaLeon** [MarcoGorelli/narwhals#46]
This:

```
integers=[0, 0, 0]
other_integers=[0, 0, 0]
floats=[0.0, 0.0, 0.0]
cols_left = ['a']
cols_right = ['a']

df_polars = pl.DataFrame({"a": integers, "b": other_integers, "c": floats})
df_pandas = pd.DataFrame({"a": integers, "b": other_integers, "c": floats})
df = nw.DataFrame(df_polars)
other_df = nw.DataFrame(df_pandas)
dframe = df.join(other_df, left_on=cols_left, right_on=cols_right, how="inner")
```
Gives:
```
Traceback (most recent call last):
  File "/Users/dealeon/projects/narwhals2/narwhals/tests/t.py", line 25, in <module>
    dframe = df.join(other_df, left_on=cols_left, right_on=cols_right, how="inner")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dealeon/projects/narwhals2/narwhals/narwhals/dataframe.py", line 997, in join
    return super().join(other, how=how, left_on=left_on, right_on=right_on)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dealeon/projects/narwhals2/narwhals/narwhals/dataframe.py", line 150, in join
    self._dataframe.join(
  File "/Users/dealeon/projects/narwhals2/narwhals/.venv2/lib/python3.12/site-packages/polars/dataframe/frame.py", line 6389, in join
    raise TypeError(msg)
TypeError: expected `other` join table to be a DataFrame, got 'PandasDataFrame'
```

**Comment by DeaMariaLeon** [comment]
Ok, got it. Sorry for the noise then.

It works with all (or at least many) of other examples (joining a polars and pandas df). Was it just good luck?  ;-)
